# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.crossImg = QtWidgets.QLabel(self.centralwidget)
        self.crossImg.setGeometry(QtCore.QRect(80, 90, 141, 141))
        self.crossImg.setText("")
        self.crossImg.setPixmap(QtGui.QPixmap("crossPlay.png"))
        self.crossImg.setObjectName("crossImg")
        self.crossBtn = QtWidgets.QPushButton(self.centralwidget)
        self.crossBtn.setGeometry(QtCore.QRect(100, 240, 113, 32))
        self.crossBtn.setObjectName("crossBtn")
        self.circleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.circleBtn.setGeometry(QtCore.QRect(320, 240, 113, 32))
        self.circleBtn.setObjectName("circleBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.circleImg = QtWidgets.QLabel(self.centralwidget)
        self.circleImg.setGeometry(QtCore.QRect(360, 150, 60, 16))
        self.circleImg.setObjectName("circleImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.crossBtn.setText(_translate("MainWindow", "cross"))
        self.circleBtn.setText(_translate("MainWindow", "circle"))
        self.label.setText(_translate("MainWindow", "Which one you chose?"))
        self.label_2.setText(_translate("MainWindow", "or"))
        self.circleImg.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
